#!/bin/bash

# A wrapper script for mapping (mamba env create {...} -> micromamba create {...})

USAGE="Usage: $0 env create ..."

if [ $# -lt 4 ] || [ "$1" != env ] || [ "$2" != create ]
then
  echo "$USAGE"
  exit 1
fi

shift 2

echo "$@"

#micromamba create "$@"